"use client";

import React, { useState, useRef } from "react";
import { motion, AnimatePresence } from "framer-motion";
import {
  Upload,
  FileText,
  ArrowRight,
  Download,
  Copy,
  Check,
  Brain,
  GitCompare,
  FileSearch,
  Highlighter,
  DownloadCloud,
  ChevronRight,
  Info,
  Scale,
  Sparkles
} from "lucide-react";

export default function HomePage() {
  const [originalText, setOriginalText] = useState("");
  const [uploadedFile, setUploadedFile] = useState<File | null>(null);
  const [isAnalyzing, setIsAnalyzing] = useState(false);
  const [copied, setCopied] = useState(false);
  const [dragActive, setDragActive] = useState(false);
  const [fileDetails, setFileDetails] = useState<{ name: string; size: string } | null>(null);

  // Results state
  const [results, setResults] = useState<{
    detected_ipc_sections: string[];
    mapped_bns_sections: string[];
    explanations: string[];
    annotated_text: string;
  } | null>(null);

  const fileInputRef = useRef<HTMLInputElement>(null);

  // Trigger file selection
  const handleUploadClick = () => {
    fileInputRef.current?.click();
  };

  // Handle drag events
  const handleDrag = (e: React.DragEvent) => {
    e.preventDefault();
    e.stopPropagation();
    if (e.type === "dragenter" || e.type === "dragover") {
      setDragActive(true);
    } else if (e.type === "dragleave") {
      setDragActive(false);
    }
  };

  // Handle drop
  const handleDrop = (e: React.DragEvent) => {
    e.preventDefault();
    e.stopPropagation();
    setDragActive(false);

    if (e.dataTransfer.files && e.dataTransfer.files[0]) {
      processFile(e.dataTransfer.files[0]);
    }
  };

  // Handle file input change
  const handleFileChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    if (e.target.files && e.target.files[0]) {
      processFile(e.target.files[0]);
    }
  };

  // Read and process the uploaded file
  const processFile = (file: File) => {
    const fileType = file.name.split(".").pop()?.toLowerCase();
    
    if (fileType !== "pdf") {
      alert("Unsupported file format. Please upload a PDF document.");
      return;
    }

    const sizeStr = (file.size / 1024).toFixed(1) + " KB";
    setFileDetails({ name: file.name, size: sizeStr });
    setUploadedFile(file);
    setOriginalText(`[PDF Document Selected: ${file.name}]\n\nClick "Analyze & Convert" to send this document to n8n for parsing and mapping.`);
  };

  // Run the analysis API
  const handleAnalyze = async () => {
    if (!uploadedFile) {
      alert("Please upload a PDF document first.");
      return;
    }

    setIsAnalyzing(true);
    try {
      const formData = new FormData();
      formData.append("file", uploadedFile);
      const response = await fetch("/api/analyze-document", {
        method: "POST",
        body: formData,
      });

      if (!response.ok) {
        const errData = await response.json().catch(() => ({}));
        throw new Error(errData.error || "Analysis failed");
      }

      const data = await response.json();
      setResults(data);
      
      // Update originalText state with extracted raw text if returned by backend
      if (data.raw_text) {
        setOriginalText(data.raw_text);
      }

      // Scroll to results section smoothly
      setTimeout(() => {
        document.getElementById("results-section")?.scrollIntoView({ behavior: "smooth" });
      }, 150);
    } catch (error: unknown) {
      console.error(error);
      const errMsg = error instanceof Error ? error.message : "Error analyzing the document. Please check your API configuration.";
      alert(errMsg);
    } finally {
      setIsAnalyzing(false);
    }
  };

  // Copy result to clipboard
  const handleCopy = () => {
    if (!results) return;
    
    // Strip HTML tags for clean copy
    const tempElement = document.createElement("div");
    tempElement.innerHTML = results.annotated_text;
    const textToCopy = tempElement.textContent || tempElement.innerText || "";
    
    navigator.clipboard.writeText(textToCopy);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  // Download reports
  const handleDownload = (format: "txt" | "pdf") => {
    if (!results) return;

    const tempElement = document.createElement("div");
    tempElement.innerHTML = results.annotated_text;
    const plainText = tempElement.textContent || tempElement.innerText || "";

    const reportHeader = `==================================================\nIPC to BNS Mapping Report\nGenerated by IPC-BNS Legal Mapper\nDate: ${new Date().toLocaleDateString()}\n==================================================\n\n`;
    const sectionsText = `Detected IPC Sections: ${results.detected_ipc_sections.join(", ") || "None"}\nMapped BNS Sections: ${results.mapped_bns_sections.join(", ") || "None"}\n\nExplanations:\n${results.explanations.map((exp, i) => `${i + 1}. ${exp}`).join("\n")}\n\n==================================================\nAnnotated Text:\n==================================================\n${plainText}`;

    const blob = new Blob([reportHeader + sectionsText], { type: "text/plain;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.download = `IPC_BNS_Report_${Date.now()}.${format}`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  return (
    <div className="flex-grow pb-16 transition-colors duration-300">
      
      {/* Hero Section */}
      <section className="relative overflow-hidden py-20 lg:py-28 bg-gradient-to-b from-primary/5 via-background to-background">
        <div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8 text-center relative z-10">
          
          {/* Badge */}
          <motion.div
            initial={{ opacity: 0, y: -20 }}
            animate={{ opacity: 1, y: 0 }}
            className="inline-flex items-center gap-1.5 rounded-full border border-primary/20 bg-primary/10 px-3.5 py-1 text-xs font-semibold text-primary mb-6"
          >
            <Sparkles className="h-3.5 w-3.5 animate-pulse" />
            Empowering Legal Tech Transition
          </motion.div>

          {/* Headline */}
          <motion.h1
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.1 }}
            className="text-4xl font-extrabold tracking-tight text-foreground sm:text-6xl max-w-4xl mx-auto leading-tight"
          >
            Convert <span className="text-primary">IPC References</span> to BNS Instantly
          </motion.h1>

          {/* Subheadline */}
          <motion.p
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.2 }}
            className="mt-6 text-lg text-foreground/75 max-w-2xl mx-auto leading-relaxed"
          >
            Upload legal PDF documents to automatically identify IPC sections and map them to corresponding BNS provisions with explanations.
          </motion.p>

          {/* Call-to-action buttons */}
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.3 }}
            className="mt-10 flex flex-wrap justify-center gap-4"
          >
            <button
              onClick={() => {
                document.getElementById("analyzer-widget")?.scrollIntoView({ behavior: "smooth" });
              }}
              className="flex items-center gap-2 rounded-xl bg-primary text-primary-foreground px-6 py-3.5 text-sm font-semibold shadow-lg hover:bg-primary/95 transition-all transform hover:-translate-y-0.5 cursor-pointer"
            >
              <Upload className="h-4.5 w-4.5" />
              Upload PDF
            </button>
          </motion.div>

          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            transition={{ delay: 0.4 }}
            className="mt-4 text-xs text-foreground/50"
          >
            Supported Format: PDF
          </motion.div>

        </div>

        {/* Decorative background grid */}
        <div className="absolute inset-0 bg-[linear-gradient(to_right,#8080800a_1px,transparent_1px),linear-gradient(to_bottom,#8080800a_1px,transparent_1px)] bg-[size:14px_24px] [mask-image:radial-gradient(ellipse_60%_50%_at_50%_0%,#000_70%,transparent_100%)]"></div>
      </section>

      {/* Main Analyzer widget */}
      <section id="analyzer-widget" className="mx-auto max-w-5xl px-4 sm:px-6 lg:px-8 -mt-8 relative z-20">
        <div className="rounded-2xl border border-border-color bg-card shadow-xl overflow-hidden transition-colors duration-300">
          
          <div className="p-6 space-y-6">
            {/* Ingestion Area */}
            <div
              onDragEnter={handleDrag}
              onDragOver={handleDrag}
              onDragLeave={handleDrag}
              onDrop={handleDrop}
              className={`flex flex-col items-center justify-center border-2 border-dashed rounded-xl p-10 transition-all ${
                dragActive
                  ? "border-primary bg-primary/5"
                  : "border-border-color bg-background hover:bg-muted/10"
              }`}
            >
              <input
                type="file"
                ref={fileInputRef}
                onChange={handleFileChange}
                accept=".pdf"
                className="hidden"
              />
              
              <div className="flex h-12 w-12 items-center justify-center rounded-full bg-primary/10 text-primary mb-4">
                <DownloadCloud className="h-6 w-6" />
              </div>
              
              <p className="text-sm font-semibold text-foreground text-center">
                Drop your legal PDF document here or{" "}
                <button
                  onClick={handleUploadClick}
                  className="text-primary hover:underline font-bold cursor-pointer"
                >
                  click to upload
                </button>
              </p>
              <p className="text-xs text-foreground/50 mt-2">
                Supported format: PDF (Max size 10MB)
              </p>

              {fileDetails && (
                <div className="mt-6 flex items-center gap-3 rounded-lg border border-primary/20 bg-primary/5 px-4 py-2 text-xs font-semibold text-primary">
                  <FileText className="h-4 w-4" />
                  <span>{fileDetails.name} ({fileDetails.size})</span>
                </div>
              )}
            </div>

            {/* Action Buttons */}
            <div className="flex justify-end">
              <button
                onClick={handleAnalyze}
                disabled={isAnalyzing || !uploadedFile}
                className="flex items-center gap-2 rounded-xl bg-primary text-primary-foreground px-6 py-3 text-sm font-semibold shadow-md hover:bg-primary/95 disabled:opacity-50 disabled:cursor-not-allowed transition-all cursor-pointer"
              >
                {isAnalyzing ? (
                  <>
                    <svg className="animate-spin -ml-1 mr-3 h-5 w-5 text-white" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
                      <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"></circle>
                      <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
                    </svg>
                    Analyzing...
                  </>
                ) : (
                  <>
                    Analyze & Convert
                    <ArrowRight className="h-4 w-4" />
                  </>
                )}
              </button>
            </div>

          </div>
        </div>
      </section>

      {/* Results Section */}
      <AnimatePresence>
        {results && (
          <motion.section
            id="results-section"
            initial={{ opacity: 0, y: 30 }}
            animate={{ opacity: 1, y: 0 }}
            exit={{ opacity: 0, y: 30 }}
            className="mx-auto max-w-6xl px-4 sm:px-6 lg:px-8 mt-16 scroll-mt-24"
          >
            <div className="rounded-2xl border border-border-color bg-card shadow-xl overflow-hidden p-6 space-y-6">
              
              <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between border-b border-border-color pb-4 gap-4">
                <div>
                  <h2 className="text-xl font-bold tracking-tight text-foreground flex items-center gap-2">
                    <Scale className="h-5.5 w-5.5 text-primary" />
                    Conversion Results
                  </h2>
                  <p className="text-xs text-foreground/50 mt-1">
                    Detected sections and mapped equivalents shown side-by-side.
                  </p>
                </div>
                
                {/* Download and copy tools */}
                <div className="flex items-center gap-2">
                  <button
                    onClick={handleCopy}
                    className="flex items-center gap-1.5 rounded-lg border border-border-color bg-card text-foreground px-3 py-2 text-xs font-semibold hover:bg-muted/50 transition-all cursor-pointer"
                  >
                    {copied ? <Check className="h-3.5 w-3.5 text-green-600" /> : <Copy className="h-3.5 w-3.5" />}
                    {copied ? "Copied!" : "Copy Result"}
                  </button>
                  <button
                    onClick={() => handleDownload("pdf")}
                    className="flex items-center gap-1.5 rounded-lg border border-border-color bg-card text-foreground px-3 py-2 text-xs font-semibold hover:bg-muted/50 transition-all cursor-pointer"
                  >
                    <Download className="h-3.5 w-3.5" />
                    PDF Report
                  </button>
                  <button
                    onClick={() => handleDownload("txt")}
                    className="flex items-center gap-1.5 rounded-lg border border-border-color bg-card text-foreground px-3 py-2 text-xs font-semibold hover:bg-muted/50 transition-all cursor-pointer"
                  >
                    <Download className="h-3.5 w-3.5" />
                    TXT Report
                  </button>
                </div>
              </div>

              {/* Highlights Legend */}
              <div className="flex flex-wrap gap-4 text-xs font-semibold border-b border-border-color/50 pb-4">
                <span className="text-foreground/60 flex items-center">Legend:</span>
                <span className="flex items-center gap-1.5 px-2 py-0.5 bg-blue-100 dark:bg-blue-950/40 border border-blue-200 dark:border-blue-800 text-blue-800 dark:text-blue-300 rounded">
                  IPC Sections (Blue)
                </span>
                <span className="flex items-center gap-1.5 px-2 py-0.5 bg-green-100 dark:bg-green-950/40 border border-green-200 dark:border-green-800 text-green-800 dark:text-green-300 rounded">
                  BNS Sections (Green)
                </span>
                <span className="flex items-center gap-1.5 px-2 py-0.5 bg-amber-50 dark:bg-amber-950/30 border border-amber-200/50 dark:border-amber-800/30 text-amber-800 dark:text-amber-300 rounded italic">
                  Descriptions (Light Yellow)
                </span>
              </div>

              {/* Full Width Layout */}
              <div className="grid grid-cols-1 gap-6">
                
                {/* Left Panel: Original Text */}
                <div className="space-y-2">
                  <span className="text-xs font-bold uppercase tracking-wider text-foreground/50">
                    Original Document Text
                  </span>
                  <div className="h-[400px] overflow-y-auto rounded-xl border border-border-color bg-muted/10 p-4 text-sm font-normal text-foreground/80 whitespace-pre-wrap leading-relaxed">
                    {originalText}
                  </div>
                </div>

                {/* Right Panel: Annotated Text */}
                <div className="space-y-2">
                  <span className="text-xs font-bold uppercase tracking-wider text-foreground/50 flex items-center gap-1">
                    Annotated Conversion
                    <span className="text-[10px] bg-primary/10 text-primary px-1.5 py-0.5 rounded font-normal uppercase">
                      Live Map
                    </span>
                  </span>
                  <div
                    className="h-[400px] overflow-y-auto rounded-xl border border-border-color bg-background p-4 text-sm font-normal text-foreground leading-relaxed select-text"
                    dangerouslySetInnerHTML={{ __html: results.annotated_text }}
                  />
                </div>

              </div>

              {/* Explanation Summary Cards */}
              {results.explanations.length > 0 && (
                <div className="mt-6 border-t border-border-color/60 pt-6 space-y-3">
                  <h3 className="text-sm font-bold text-foreground flex items-center gap-1.5">
                    <Info className="h-4.5 w-4.5 text-primary" />
                    Specific Legal Mapping Explanations
                  </h3>
                  <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                    {results.explanations.map((exp, idx) => (
                      <div key={idx} className="rounded-xl border border-border-color bg-muted/20 p-4 text-xs font-medium text-foreground/80 leading-relaxed shadow-sm">
                        {exp}
                      </div>
                    ))}
                  </div>
                </div>
              )}

            </div>
          </motion.section>
        )}
      </AnimatePresence>

      {/* Process Flow Section */}
      <section className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8 mt-24">
        <div className="text-center space-y-3">
          <h2 className="text-2xl font-bold tracking-tight text-foreground sm:text-3xl">
            How the Legal Mapper Works
          </h2>
          <p className="text-sm text-foreground/60 max-w-lg mx-auto">
            A secure six-step automated sequence converting legacy references to the updated codes.
          </p>
        </div>

        <div className="mt-12 grid grid-cols-1 gap-6 sm:grid-cols-2 lg:grid-cols-6">
          {[
            { step: "1", title: "Upload PDF", desc: "Submit PDF document containing references." },
            { step: "2", title: "Extract Text", desc: "System extracts textual contents securely." },
            { step: "3", title: "Identify Sections", desc: "AI scans for historical IPC references." },
            { step: "4", title: "Retrieve BNS", desc: "Maps records to corresponding BNS database." },
            { step: "5", title: "Explain Provisions", desc: "Generates legal context explanations." },
            { step: "6", title: "Review Highlights", desc: "Output comparisons instantly side-by-side." }
          ].map((item, idx) => (
            <div
              key={idx}
              className="relative rounded-xl border border-border-color bg-card p-5 shadow-sm flex flex-col justify-between"
            >
              <div>
                <span className="flex h-8 w-8 items-center justify-center rounded-full bg-primary/10 text-xs font-bold text-primary mb-3">
                  {item.step}
                </span>
                <h3 className="text-sm font-bold text-foreground">
                  {item.title}
                </h3>
                <p className="text-xs text-foreground/60 mt-1 leading-relaxed">
                  {item.desc}
                </p>
              </div>
              
              {idx < 5 && (
                <div className="hidden lg:block absolute -right-3.5 top-1/2 -translate-y-1/2 z-20 text-border-color">
                  <ChevronRight className="h-5 w-5" />
                </div>
              )}
            </div>
          ))}
        </div>
      </section>

      {/* Features Section */}
      <section className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8 mt-28">
        <div className="text-center space-y-3">
          <h2 className="text-2xl font-bold tracking-tight text-foreground sm:text-3xl">
            Core Features for Legal Professionals
          </h2>
          <p className="text-sm text-foreground/60 max-w-lg mx-auto">
            Modern utilities designed to accelerate legal casework and document migration.
          </p>
        </div>

        <div className="mt-12 grid grid-cols-1 gap-6 sm:grid-cols-2 lg:grid-cols-3">
          {[
            {
              icon: <FileSearch className="h-6 w-6 text-primary" />,
              title: "IPC Detection",
              desc: "Automatically identifies IPC references within uploaded charge-sheets, FIRs, and pleadings."
            },
            {
              icon: <GitCompare className="h-6 w-6 text-accent-purple" />,
              title: "BNS Mapping",
              desc: "Accurately maps legacy IPC sections to corresponding new Bharatiya Nyaya Sanhita (BNS) provisions."
            },
            {
              icon: <Brain className="h-6 w-6 text-accent-orange" />,
              title: "AI Explanations",
              desc: "Provides concise summaries detailing definition revisions, structural shifts, or penalty reforms."
            },
            {
              icon: <FileText className="h-6 w-6 text-primary" />,
              title: "Document Processing",
              desc: "Processes PDF uploads for rapid conversion."
            },
            {
              icon: <Highlighter className="h-6 w-6 text-accent-purple" />,
              title: "Highlighted Comparison",
              desc: "Provides clean color-coded legal highlight overlays to track changes inside the original text."
            },
            {
              icon: <Download className="h-6 w-6 text-accent-orange" />,
              title: "Export Reports",
              desc: "Exports generated annotated documents into printable PDF and plain-text files with a single click."
            }
          ].map((feat, idx) => (
            <div
              key={idx}
              className="rounded-2xl border border-border-color bg-card p-6 shadow-sm hover:shadow-md transition-all flex gap-4 group"
            >
              <div className="flex h-12 w-12 shrink-0 items-center justify-center rounded-xl bg-muted group-hover:bg-primary/10 transition-colors">
                {feat.icon}
              </div>
              <div className="space-y-1">
                <h3 className="text-base font-bold text-foreground">
                  {feat.title}
                </h3>
                <p className="text-sm text-foreground/60 leading-relaxed">
                  {feat.desc}
                </p>
              </div>
            </div>
          ))}
        </div>
      </section>

    </div>
  );
}
